In [2]:
%pip install numpy


   ---------------------------------------- 0.0/12.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.4 MB ? eta -:--:--
   --- ------------------------------------ 1.0/12.4 MB 5.6 MB/s eta 0:00:03
   ------- -------------------------------- 2.4/12.4 MB 6.3 MB/s eta 0:00:02
   -------------- ------------------------- 4.5/12.4 MB 7.8 MB/s eta 0:00:02
   ----------------------- ---------------- 7.3/12.4 MB 9.2 MB/s eta 0:00:01
   ------------------------------- -------- 9.7/12.4 MB 9.5 MB/s eta 0:00:01
   ------------------------------------- -- 11.5/12.4 MB 9.4 MB/s eta 0:00:01
   ---------------------------------------- 12.4/12.4 MB 9.3 MB/s  0:00:01
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [5]:
# Step 1: Import NumPy
import numpy as np

# Step 2: Create a 1D array representing years of experience
years_exp = np.array([1, 3 , 5, 7 , 10])
print("Years of Experience:", years_exp)

# Step 3: Create a 2D array representing sample salaries( in thousands )
salaries= np.array([[50, 60, 70], [80, 90, 100]])
print("Salary Matrix:\n", salaries)

# Sep 4: Create an array of zeros and ones for placeholder analysis
zeros_array = np.zeros((2, 2)) # 2x2 zeros
ones_array = np.ones((2, 3)) # 2x3 ones
print("Zeros Array:\n", zeros_array)
print("Ones Array:\n", ones_array)

# Updated Step 2: Added 12 and 15
years_exp = np.array([1, 3, 5, 7, 10, 12, 15])
print("Years of Experience:", years_exp)

# Updated Step 3: Added a 3rd row to match the 3x3 requirement often seen in labs
# (Make sure each row has the same number of elements!)
salaries = np.array([[50, 60, 70], 
                     [80, 90, 100], 
                     [110, 120, 130]])

print("Salary Matrix:\n", salaries)

# Step 5: Create a 3x3 identity matrix
identity_matrix = np.eye(3)
print("3x3 Identity Matrix:\n", identity_matrix)




Years of Experience: [ 1  3  5  7 10]
Salary Matrix:
 [[ 50  60  70]
 [ 80  90 100]]
Zeros Array:
 [[0. 0.]
 [0. 0.]]
Ones Array:
 [[1. 1. 1.]
 [1. 1. 1.]]
Years of Experience: [ 1  3  5  7 10 12 15]
Salary Matrix:
 [[ 50  60  70]
 [ 80  90 100]
 [110 120 130]]
3x3 Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [7]:
# Step 1: Element-wise addition
exp_plus_5 = years_exp + 5 # Add 5 years to all experience values
print("Years + 5:", exp_plus_5)

# Step 2: Element-wise multiplication
exp_times_2 = years_exp * 2 # Multiply all values by 2
print("Years * 2:", exp_times_2)

# Step 3: Dot product (simulate salary projections)
sample1 = np.array([1, 2, 3])
sample2 = np.array([4, 5, 6])
dot_result = np.dot(sample1, sample2)
print("Dot Product:", dot_result)

# Subtraction: Subtracting 1 from every year of experience
exp_minus_1 = years_exp - 1
print("Years - 1:", exp_minus_1)

# Division: Halving the salaries (e.g., for a 6-month projection)
salaries_half = salaries / 2
print("Salaries / 2:\n", salaries_half)

# Natural Exponential: e^x for each element in years_exp
exp_values = np.exp(years_exp)
print("Exponential of Years:", exp_values)

# Natural Logarithm: ln(x) for each element in salaries
# Note: Salaries must be greater than 0
log_salaries = np.log(salaries)
print("Log of Salaries:\n", log_salaries)

Years + 5: [ 6  8 10 12 15 17 20]
Years * 2: [ 2  6 10 14 20 24 30]
Dot Product: 32
Years - 1: [ 0  2  4  6  9 11 14]
Salaries / 2:
 [[25. 30. 35.]
 [40. 45. 50.]
 [55. 60. 65.]]
Exponential of Years: [2.71828183e+00 2.00855369e+01 1.48413159e+02 1.09663316e+03
 2.20264658e+04 1.62754791e+05 3.26901737e+06]
Log of Salaries:
 [[3.91202301 4.09434456 4.24849524]
 [4.38202663 4.49980967 4.60517019]
 [4.70048037 4.78749174 4.86753445]]


In [10]:
# Indexing and Slicing
# Step 1: Access individual element
print("First year of experience:", years_exp[0])

# Step 2: Slice arrays
print("First two salaries:", salaries[0, :2]) # First two elements of first row

# Step 3: Access all rows for a specific column
print("Second column salaries:", salaries[:, 1])

# Step 4: Negative indexing
print("Last year of experience:", years_exp[-1])

# Reversing the years_exp array
reversed_years = years_exp[::-1]
print("Reversed years:", reversed_years)

# Subgrouping 2D Arrays
subgroup = salaries[0:2, 0:2]
print("2x2 Subgroup of salaries:\n", subgroup)

# Example: Get all rows, but only the middle columns (index 1 to 2)
middle_cols = salaries[:, 1:3]

First year of experience: 1
First two salaries: [50 60]
Second column salaries: [ 60  90 120]
Last year of experience: 15
Reversed years: [15 12 10  7  5  3  1]
2x2 Subgroup of salaries:
 [[50 60]
 [80 90]]


In [12]:
# Reshaping and Dimensions

# Step 1: Reshape 1D array into 2x3 matrix for batch analysis
reshaped_exp = np.reshape(np.arange(1, 7), (2, 3))
print("Reshaped Experience Array:\n", reshaped_exp)

# Step 2: Flatten 2D arrays back into 1D
flattened_exp = reshaped_exp.flatten()
print("Flattened Array:", flattened_exp)

# Step 3: Transpose example
print("Transposed Array:\n", reshaped_exp.T)

# Updated: Try It Results
data = np.arange(1, 7)

# Reshape to 3 rows and 2 columns
reshaped_3x2 = data.reshape(3, 2)
print("Try It Results:")
print("\nReshaped into 3x2:\n", reshaped_3x2)

Reshaped Experience Array:
 [[1 2 3]
 [4 5 6]]
Flattened Array: [1 2 3 4 5 6]
Transposed Array:
 [[1 4]
 [2 5]
 [3 6]]
Try It Results:

Reshaped into 3x2:
 [[1 2]
 [3 4]
 [5 6]]


In [ ]:
# Broadcasing in NumPy
# Step 1: Add a bonus array to salaries using broadcasting
bonus = np.array([5, 10, 15])
salaries_with_bonus = salaries + bonus # Adds corresponding bonus to each column
print("Salaries after bonus:\n", salaries_with_bonus)

# Updated: Try It Results
scaling_factor = 1.50

# Multiply the entire salaries matrix by the factor
scaled_salaries = salaries * scaling_factor

print("Try It Results:")
print(f"\nSalaries after {scaling_factor} scaling factor:\n", scaled_salaries)

Salaries after bonus:
 [[ 55  70  85]
 [ 85 100 115]
 [115 130 145]]
Try It Results:

Salaries after 1.5 scaling factor:
 [[ 75.  90. 105.]
 [120. 135. 150.]
 [165. 180. 195.]]


In [15]:
# Statistical Operations

# Step 1: Mean of years of experience
print("Mean experience:", np.mean(years_exp))

# Step 2: Standard deviation of experience
print("Std deviation of experience:", np.std(years_exp))

# Step 3: Max and Min salaries
print("Max salary:", np.max(salaries), "Min salary:", np.min(salaries))

# Step 4: Sum of salaries
print("Sum of all salaries:", np.sum(salaries))

# Updated: Try It Results
# Compute median for years of experience
median_exp = np.median(years_exp)
print("\nTry It Results:")
print("\nMedian experience:", median_exp)

# Compute the 25th and 75th percentiles for salaries
p25 = np.percentile(salaries, 25)
p75 = np.percentile(salaries, 75)

print(f"25th percentile of salaries: {p25}")
print(f"75th percentile of salaries: {p75}")

Mean experience: 7.571428571428571
Std deviation of experience: 4.655477353371521
Max salary: 130 Min salary: 50
Sum of all salaries: 810

Try It Results:

Median experience: 7.0
25th percentile of salaries: 70.0
75th percentile of salaries: 110.0


In [16]:
# NumPy Functions on Arrays
# Step 1: Apply trigonometric functions
angles = np.array([0, np.pi/4, np.pi/2])
print("Sine of angles:", np.sin(angles))
print("Cosine of angles:", np.cos(angles))

# Step 2: Apply function along rows (sum salaries per person)
salary_sums = np.apply_along_axis(np.sum, 1, salaries)
print("Sum of Salaries per person:", salary_sums)

# Updated: Try It Results
# Apply square root to years of experience
sqrt_exp = np.sqrt(years_exp)
print("\nTry It Results:")
print("\nSquare root of experience:", sqrt_exp)

# Define a custom function
def calculate_tax(salary_row):
    return salary_row * 0.10

# Apply it along axis 1 (rows)
tax_per_person = np.apply_along_axis(calculate_tax, 1, salaries)

print("\n10% Tax deduction per person (by row):\n", tax_per_person)

Sine of angles: [0.         0.70710678 1.        ]
Cosine of angles: [1.00000000e+00 7.07106781e-01 6.12323400e-17]
Sum of Salaries per person: [180 270 360]

Try It Results:

Square root of experience: [1.         1.73205081 2.23606798 2.64575131 3.16227766 3.46410162
 3.87298335]

10% Tax deduction per person (by row):
 [[ 5.  6.  7.]
 [ 8.  9. 10.]
 [11. 12. 13.]]


In [21]:
!pip install pandas numpy


   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   -- ------------------------------------- 0.5/9.9 MB 4.7 MB/s eta 0:00:03
   -------- ------------------------------- 2.1/9.9 MB 7.4 MB/s eta 0:00:02
   ------------------ --------------------- 4.5/9.9 MB 8.5 MB/s eta 0:00:01
   ------------------------- -------------- 6.3/9.9 MB 9.3 MB/s eta 0:00:01
   -------------------------------------- - 9.4/9.9 MB 10.0 MB/s eta 0:00:01
   ---------------------------------------- 9.9/9.9 MB 9.8 MB/s  0:00:01

   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -----


[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
# Integrating NumPy and Pandas for Analysis
import pandas as pd
import numpy as np 
# Step 1: Create a NumPy array of random data
data = np.random.randint(1, 50, size=(5, 3))

# Step 2: Convert the array into a DataFrame
df_data = pd.DataFrame(data, columns=['X', 'Y', 'Z'])
print("Generated Data:\n", df_data)

# Step 3: Apply NumPy functions to DataFrame columns
df_data['Log_X'] = np.log(df_data['X'])
df_data['Sqrt_Y'] = np.sqrt(df_data['Y'])
print("DataFrame with NumPy Transformations:\n", df_data)

# Step 4: Analyze data using Pandas correlation
print("Correlation Matrix:\n", df_data.corr())

# Compute statistics for column 'X'
mean_x = np.mean(df_data['X'])
median_x = np.median(df_data['X'])

print(f"Column X - Mean: {mean_x:.2f}, Median: {median_x}")

# Pro Tip: To get means for ALL columns at once:
# np.mean(df_data, axis=0)

# Create new columns using NumPy transformations
df_data['X_Squared'] = np.square(df_data['X'])
df_data['Y_Exp'] = np.exp(df_data['Y'])

print("Transformed DataFrame:\n", df_data[['X', 'X_Squared', 'Y', 'Y_Exp']])

Generated Data:
     X   Y   Z
0  26  16   6
1  24  12  22
2  46  28  14
3  39  42  23
4   8  18  39
DataFrame with NumPy Transformations:
     X   Y   Z     Log_X    Sqrt_Y
0  26  16   6  3.258097  4.000000
1  24  12  22  3.178054  3.464102
2  46  28  14  3.828641  5.291503
3  39  42  23  3.663562  6.480741
4   8  18  39  2.079442  4.242641
Correlation Matrix:
                X         Y         Z     Log_X    Sqrt_Y
X       1.000000  0.644580 -0.606368  0.965659  0.649366
Y       0.644580  1.000000  0.012168  0.527638  0.996556
Z      -0.606368  0.012168  1.000000 -0.730857  0.007618
Log_X   0.965659  0.527638 -0.730857  1.000000  0.517484
Sqrt_Y  0.649366  0.996556  0.007618  0.517484  1.000000
Column X - Mean: 28.60, Median: 26.0
Transformed DataFrame:
     X  X_Squared   Y         Y_Exp
0  26        676  16  8.886111e+06
1  24        576  12  1.627548e+05
2  46       2116  28  1.446257e+12
3  39       1521  42  1.739275e+18
4   8         64  18  6.565997e+07


In [5]:
# Importing and Summarizing Data Using Pandas
# Step 1: Save the DataFrame to a CSV file
df_data.to_csv('sample_data.csv', index=False)
print("Data saved to 'sample_data.csv'.")

# Step 2: Load the CSV file back into a new DataFrame
np.set_printoptions(precision=4, suppress=True)
df_imported = pd.read_csv('sample_data.csv')
print("\nImported DataFrame:\n", df_imported)

# Step 3: Generate summary statistics
np.set_printoptions(precision=4, suppress=True)
summary_stats = df_imported.describe()
print("\nSummary Statistics:\n", summary_stats)

# Step 4: Display column means and standard deviations
np.set_printoptions(precision=4, suppress=True)
print("\nColumn Means:\n", df_imported.mean())
print("\nColumn Standard Deviations:\n", df_imported.std())

# Create a new column 'Sum_XY' by adding X and Y
df_imported['Sum_XY'] = df_imported['X'] + df_imported['Y']

# You can also do more complex math, like a weighted average
df_imported['Weighted_Z'] = (df_imported['Z'] * 0.5) + (df_imported['X'] * 0.5)

print("Updated DataFrame with new columns:\n", df_imported.head())

# Save to a new file name to avoid overwriting your original source
df_imported.to_csv('processed_data.csv', index=False)

print("Modified data successfully saved to 'processed_data.csv'.")



Data saved to 'sample_data.csv'.

Imported DataFrame:
     X   Y   Z     Log_X    Sqrt_Y  X_Squared         Y_Exp
0  26  16   6  3.258097  4.000000        676  8.886111e+06
1  24  12  22  3.178054  3.464102        576  1.627548e+05
2  46  28  14  3.828641  5.291503       2116  1.446257e+12
3  39  42  23  3.663562  6.480741       1521  1.739275e+18
4   8  18  39  2.079442  4.242641         64  6.565997e+07

Summary Statistics:
                X          Y          Z     Log_X    Sqrt_Y   X_Squared  \
count   5.000000   5.000000   5.000000  5.000000  5.000000     5.00000   
mean   28.600000  23.200000  20.800000  3.201559  4.695797   990.60000   
std    14.690133  12.049896  12.275993  0.683662  1.198692   818.12334   
min     8.000000  12.000000   6.000000  2.079442  3.464102    64.00000   
25%    24.000000  16.000000  14.000000  3.178054  4.000000   576.00000   
50%    26.000000  18.000000  22.000000  3.258097  4.242641   676.00000   
75%    39.000000  28.000000  23.000000  3.663562  5

In [11]:
# Data Grouping and Aggregation
# Step 1: Load the dataset (This is now working!)
df_kaggle = pd.read_csv('survey_results_public.csv')

# Step 2: Select columns (Fixed the names to match the CSV)
# Note: In the 2023 survey, compensation is 'ConvertedCompYearly'
df_subset = df_kaggle[['Country', 'EdLevel', 'YearsCodePro', 'ConvertedCompYearly']]

# Step 3: Clean the data
df_clean = df_subset.dropna().copy()

# Step 4: Categorize experience 
# We must convert 'YearsCodePro' to numbers first because it's stored as text
df_clean['YearsCodePro'] = pd.to_numeric(df_clean['YearsCodePro'], errors='coerce')
df_clean = df_clean.dropna() 

df_clean['ExperienceLevel'] = np.where(df_clean['YearsCodePro'] >= 10, 'Senior', 'Junior')

# Step 5 & 6: Group and Reset Index
grouped_data = df_clean.groupby(['Country', 'ExperienceLevel'])['ConvertedCompYearly'].mean()
grouped_data = grouped_data.reset_index()

print("Formatted Grouped Data:\n", grouped_data.head())

# Updated: Try It Results
print("Try It Results:")

# 1. Change the grouping to EdLevel
ed_group = df_clean.groupby('EdLevel')['ConvertedCompYearly'].mean().sort_values(ascending=False)
print("\n1. Average Salary by Education Level:\n", ed_group)

# 2. Compute median and standard deviation
stats_by_country = df_clean.groupby('Country')['ConvertedCompYearly'].agg(['median', 'std'])
print("\n2. Median and Std Dev per Country (Top 5):\n", stats_by_country.head())

# 3. Explore top 10 countries with highest average compensation
top_10_countries = df_clean.groupby('Country')['ConvertedCompYearly'].mean().sort_values(ascending=False).head(10).round(2)
print("\n3. Top 10 Countries by Average Compensation:\n", top_10_countries)


Formatted Grouped Data:
        Country ExperienceLevel  ConvertedCompYearly
0  Afghanistan          Junior         1.031035e+06
1  Afghanistan          Senior         3.300000e+01
2      Albania          Junior         2.564647e+04
3      Albania          Senior         1.397000e+05
4      Algeria          Junior         9.103895e+03
Try It Results:

1. Average Salary by Education Level:
 EdLevel
Primary/elementary school                                                             358681.449761
Professional degree (JD, MD, Ph.D, Ed.D, etc.)                                        159445.678094
Bachelor’s degree (B.A., B.S., B.Eng., etc.)                                          104938.502816
Master’s degree (M.A., M.S., M.Eng., MBA, etc.)                                        97124.658707
Associate degree (A.A., A.S., etc.)                                                    91136.695003
Some college/university study without earning a degree                                 90738.206916

In [1]:
# DATA AND OBSERVATION 1
import numpy as np
STUDENT_NAME = "Jan Antonio Lontao"
STUDENT_ID = 250564

np.random.seed(STUDENT_ID)
data = np.random.randint(1, STUDENT_ID % 100 + 50, size=10)
print(f"{STUDENT_NAME}'s Array:", data)

mean_val = np.mean(data)
std_val = np.std(data)
print("Mean:", mean_val, "Std Dev:", std_val)

Jan Antonio Lontao's Array: [ 38  59 108   7  81  44  79  61  63  44]
Mean: 58.4 Std Dev: 26.260997696203397


In [21]:
# DATA AND OBSERVATION 2
import numpy as np
STUDENT_NAME = "Jan Antonio Lontao"
STUDENT_ID = 250564

np.random.seed(STUDENT_ID)
matrix = np.random.randint(1, STUDENT_ID % 50 + 20, size=(3,4))
print(f"{STUDENT_NAME}'s Matrix:\n", matrix)

row_sums = np.sum(matrix, axis=1)
col_sums = np.sum(matrix, axis=0)
print("Row sums:", row_sums)
print("Column sums:", col_sums)

Jan Antonio Lontao's Matrix:
 [[ 7 17 15 19]
 [ 1 17 19  1]
 [ 7 22 18 15]]
Row sums: [58 38 62]
Column sums: [15 56 52 35]


In [3]:
# DATA AND OBSERVATION 3
import numpy as np
STUDENT_NAME = "Jan Antonio Lontao"
STUDENT_ID = 250564

np.random.seed(STUDENT_ID)
arr3d = np.random.randint(0, STUDENT_ID % 20 + 10, size=(3,3,3))
print(f"{STUDENT_NAME}'s 3D Array:\n", arr3d)

slice_mid = arr3d[:,1,:]
print("Slice[:,1,:]:\n", slice_mid)

Jan Antonio Lontao's 3D Array:
 [[[ 5 10 11]
  [ 6  0 11]
  [12 11  4]]

 [[13  9  2]
  [ 0  0  2]
  [12 10  0]]

 [[10 13  4]
  [ 6  5  1]
  [11  2  0]]]
Slice[:,1,:]:
 [[ 6  0 11]
 [ 0  0  2]
 [ 6  5  1]]


In [22]:
# DATA AND OBSERVATION 4
import numpy as np
STUDENT_NAME = "Jan Antonio Lontao"
STUDENT_ID = 250564

np.random.seed(STUDENT_ID)
x = np.random.randint(1, STUDENT_ID % 100 + 50, size=10)
filtered = x[(x>STUDENT_ID%50) & (x<STUDENT_ID%100)]
print(f"{STUDENT_NAME}'s Original:", x)
print("Filtered subset:", filtered)

Jan Antonio Lontao's Original: [ 38  59 108   7  81  44  79  61  63  44]
Filtered subset: [38 59 44 61 63 44]


In [5]:
# DATA AND OBSERVATION 5
import numpy as np
STUDENT_NAME = "Jan Antonio Lontao"
STUDENT_ID = 250564

np.random.seed(STUDENT_ID)
A = np.random.randint(1, STUDENT_ID % 50 + 20, size=(2,2))
B = np.random.randint(1, STUDENT_ID % 50 + 20, size=(2,2))
print("Matrix A:\n", A)
print("Matrix B:\n", B)

product = A @ B
det_A = np.linalg.det(A)
print("A @ B:\n", product)
print("Determinant of A:", det_A)

Matrix A:
 [[ 7 17]
 [15 19]]
Matrix B:
 [[ 1 17]
 [19  1]]
A @ B:
 [[330 136]
 [376 274]]
Determinant of A: -121.99999999999991


In [6]:
# DATA AND OBSERVATION 6
import numpy as np
STUDENT_NAME = "Jan Antonio Lontao"
STUDENT_ID = 250564

angles = np.linspace(0, 2*np.pi, 8)
sine_vals = np.sin(angles)
cos_vals = np.cos(angles)
print(f"{STUDENT_NAME}'s Angles:", angles)
print("Sine:", sine_vals)
print("Cosine:", cos_vals)

Jan Antonio Lontao's Angles: [0.         0.8975979  1.7951958  2.6927937  3.5903916  4.48798951
 5.38558741 6.28318531]
Sine: [ 0.00000000e+00  7.81831482e-01  9.74927912e-01  4.33883739e-01
 -4.33883739e-01 -9.74927912e-01 -7.81831482e-01 -2.44929360e-16]
Cosine: [ 1.          0.6234898  -0.22252093 -0.90096887 -0.90096887 -0.22252093
  0.6234898   1.        ]


In [7]:
# DATA AND OBSERVATION 7
import numpy as np
STUDENT_NAME = "Jan Antonio Lontao"
STUDENT_ID = 250564

np.random.seed(STUDENT_ID)
arr = np.random.randint(1, STUDENT_ID % 50 + 20, size=(4,4))
arr[::2, ::2] = 0
print(f"{STUDENT_NAME}'s Modified 4x4 Array:\n", arr)

Jan Antonio Lontao's Modified 4x4 Array:
 [[ 0 17  0 19]
 [ 1 17 19  1]
 [ 0 22  0 15]
 [28  1 18  6]]


In [8]:
# DATA AND OBSERVATION 8
import numpy as np
STUDENT_NAME = "Jan Antonio Lontao"
STUDENT_ID = 250564

np.random.seed(STUDENT_ID)
scores = np.random.randint(0, STUDENT_ID % 100 + 50, 10)
grades = np.where(scores>=STUDENT_ID%70,'Pass','Fail')
print(f"{STUDENT_NAME}'s Scores:", scores)
print("Grades:", grades)

Jan Antonio Lontao's Scores: [ 37  58 107   6  80  43  78  60  62  43]
Grades: ['Pass' 'Pass' 'Pass' 'Fail' 'Pass' 'Pass' 'Pass' 'Pass' 'Pass' 'Pass']


In [9]:
# DATA AND OBSERVATION 9
import numpy as np
STUDENT_NAME = "Jan Antonio Lontao"
STUDENT_ID = 250564

np.random.seed(STUDENT_ID)
arr = np.random.randint(1, STUDENT_ID % 50 + 20, size=(3,4))
flat_arr = arr.flatten()
transposed_arr = arr.T
print("Original array:\n", arr)
print("Flattened:", flat_arr)
print("Transposed:\n", transposed_arr)

Original array:
 [[ 7 17 15 19]
 [ 1 17 19  1]
 [ 7 22 18 15]]
Flattened: [ 7 17 15 19  1 17 19  1  7 22 18 15]
Transposed:
 [[ 7  1  7]
 [17 17 22]
 [15 19 18]
 [19  1 15]]


In [10]:
# DATA AND OBSERVATION 10
import numpy as np
STUDENT_NAME = "Jan Antonio Lontao"
STUDENT_ID = 250564

np.random.seed(STUDENT_ID)
arr = np.random.randint(1, STUDENT_ID % 50 + 20, (3,3))
mask = arr % 2 == 0
arr[mask] = -1
print("Array with conditional replacements:\n", arr)

Array with conditional replacements:
 [[ 7 17 15]
 [19  1 17]
 [19  1  7]]


In [11]:
# DATA AND OBSERVATION 11
import numpy as np
import pandas as pd
STUDENT_NAME = "Jan Antonio Lontao"
STUDENT_ID = 250564

np.random.seed(STUDENT_ID)
df = pd.DataFrame({
 'Name': [STUDENT_NAME]*5,
 'Score': np.random.randint(STUDENT_ID%50,
STUDENT_ID%100+50,5),
 'YearsCodePro': np.random.randint(0, STUDENT_ID%20+10,5)
})
print(df)

                 Name  Score  YearsCodePro
0  Jan Antonio Lontao     51            12
1  Jan Antonio Lontao     72            11
2  Jan Antonio Lontao     20             4
3  Jan Antonio Lontao     94            13
4  Jan Antonio Lontao     57             9


In [12]:
# DATA AND OBSERVATION 12
import numpy as np
import pandas as pd
STUDENT_NAME = "Jan Antonio Lontao"
STUDENT_ID = 250564

np.random.seed(STUDENT_ID)
df = pd.DataFrame({
'EdLevel': ['Bachelor','Master','PhD','Bachelor','Master'],
# Corrected to use a functional salary range, e.g., 40000 to 150000
'ConvertedComp': np.random.randint(40000, 150000, 5)
})
avg_salary = df.groupby('EdLevel')['ConvertedComp'].mean()
print(avg_salary)

EdLevel
Bachelor    141829.0
Master      122251.0
PhD          82630.0
Name: ConvertedComp, dtype: float64


In [13]:
# DATA AND OBSERVATION 13
import numpy as np
import pandas as pd
STUDENT_NAME = "Jan Antonio Lontao"
STUDENT_ID = 250564

np.random.seed(STUDENT_ID)
df = pd.DataFrame({
 'Country': ['Philippines','USA','UK','Canada','Germany'],
 'ConvertedComp': np.random.randint(40000, 150000, 5)
})
top5 = df.sort_values(by='ConvertedComp', ascending=False)
print(top5)

       Country  ConvertedComp
0  Philippines         149370
3       Canada         134288
4      Germany         123243
1          USA         121259
2           UK          82630


In [14]:
# DATA AND OBSERVATION 14
import numpy as np
import pandas as pd
STUDENT_NAME = "Jan Antonio Lotao"
STUDENT_ID = 250564

np.random.seed(STUDENT_ID)
df = pd.DataFrame({
 'Name':[STUDENT_NAME]*5,
 'YearsCodePro': np.random.randint(0, STUDENT_ID%20+10,5)
})
high_exp = df[df['YearsCodePro']>STUDENT_ID%10]
print(high_exp)

                Name  YearsCodePro
0  Jan Antonio Lotao             5
1  Jan Antonio Lotao            10
2  Jan Antonio Lotao            11
3  Jan Antonio Lotao             6


In [15]:
# DATA AND OBSERVATION 15
import numpy as np
import pandas as pd
STUDENT_NAME = "Jan Antonio Lontao"
STUDENT_ID = 250564

np.random.seed(STUDENT_ID)
df = pd.DataFrame({'ConvertedComp': np.random.randint(40000,
150000, 5)})
bins = [0, 50000, 100000, 150000, 200000]
labels = ['0-50k', '50-100k', '100-150k', '>150k']
df['Bracket'] = pd.cut(df['ConvertedComp'], bins=bins, labels=labels)
print(df)

   ConvertedComp   Bracket
0         149370  100-150k
1         121259  100-150k
2          82630   50-100k
3         134288  100-150k
4         123243  100-150k


In [16]:
# DATA AND OBSERVATION 16
import numpy as np
import pandas as pd
STUDENT_NAME = "Jan Antonio Lontao"
STUDENT_ID = 250564

np.random.seed(STUDENT_ID)
# Original Code Issue:
# np.random.randint(STUDENT_ID%40000, STUDENT_ID%150000, 5)
# -> np.random.randint(12345, 12345, 5) which is a zero-length range.
# Corrected Code: Using a functional salary range (40000 to 150000)
df = pd.DataFrame({'ConvertedComp': np.random.randint(40000,
150000, 5)})
df['LogComp'] = np.log(df['ConvertedComp'])
print(df)

   ConvertedComp    LogComp
0         149370  11.914182
1         121259  11.705684
2          82630  11.322128
3         134288  11.807742
4         123243  11.721913


In [17]:
# DATA AND OBSERVATION 17
import numpy as np
import pandas as pd
STUDENT_NAME = "Jan Antonio Lontao"
STUDENT_ID = 250564

np.random.seed(STUDENT_ID)
df = pd.DataFrame({
'YearsCodePro': np.random.randint(0, STUDENT_ID%20+10, 5),
'ConvertedComp': np.random.randint(40000, 150000, 5)
})
corr_matrix = df.corr()
print(corr_matrix)

               YearsCodePro  ConvertedComp
YearsCodePro       1.000000      -0.187117
ConvertedComp     -0.187117       1.000000


In [18]:
# DATA AND OBSERVATION 18
import numpy as np
import pandas as pd
STUDENT_NAME = "Jan Antonio Lontao"
STUDENT_ID = 250564

np.random.seed(STUDENT_ID)
df = pd.DataFrame({
    'EdLevel':['Bachelor', 'Master', 'PhD', 'Bachelor', 'Master'],
    'ConvertedComp': np.random.randint(40000, 150000, 5)
})

# Calculate mean, median, and standard deviation for each 'EdLevel'
summary = df.groupby('EdLevel')['ConvertedComp'].agg(['mean', 'median', 'std']).reset_index()

print(summary)

    EdLevel      mean    median           std
0  Bachelor  141829.0  141829.0  10664.584474
1    Master  122251.0  122251.0   1402.899854
2       PhD   82630.0   82630.0           NaN


In [19]:
# DATA AND OBSERVATION 19
import numpy as np
import pandas as pd
STUDENT_NAME = "Jan Antonio Lontao"
STUDENT_ID = 250564

np.random.seed(STUDENT_ID)

# Generate salaries: [100727, 136195, 130612, 100727, 95233]
df = pd.DataFrame({'ConvertedComp': np.random.randint(40000,
150000, 5)})

threshold = 110000

# Create the 'HighPay' column using np.where()
df['HighPay'] = np.where(df['ConvertedComp'] > threshold, 'Yes', 'No')

print(df)

   ConvertedComp HighPay
0         149370     Yes
1         121259     Yes
2          82630      No
3         134288     Yes
4         123243     Yes


In [20]:
# DATA AND OBSERVATION 20
import numpy as np
import pandas as pd
STUDENT_NAME = "Jan Antonio Lontao"
STUDENT_ID = 250564

np.random.seed(STUDENT_ID)

df = pd.DataFrame({
'Country': ['Philippines','USA','UK','Canada','Germany'],
'ConvertedComp': np.random.randint(40000, 150000, 5)
})

# Group by 'Country' and calculate the mean and max 'ConvertedComp'
top_countries = df.groupby('Country')['ConvertedComp'].agg(['mean','max'])
print(top_countries)

                 mean     max
Country                      
Canada       134288.0  134288
Germany      123243.0  123243
Philippines  149370.0  149370
UK            82630.0   82630
USA          121259.0  121259
